- name: printed varibles from tasks level
  hosts: mongodb
  vars_tasks:
   varibles.yaml
  tasks:
  - name: printed varibles from tasks level
    ansible.builtin.debug:
     msg: "i am learning course is {{COURSE}} and trainer is {{TRAINER}} and duration is {{DURATION}}"