- name: printed varibles from prompt level
  hosts: mongodb
  vars_prompt:
  - name: USERNAME
    prompt: enter username
    privacy: false
  - name: PASSWORD
    prompt: enter password
    privacy: true
  tasks:
  - name: printed varibles from prompt level
    ansible.builtin.debug:
     msg: "username{{USERNAME}} password{{PASSWORD}}"
